---
- name: Set Password
  hosts: vm-teste

  tasks:

  - name: Change Password
    user: 
      name: root 
      password: "{{ 'senhaAqui' | password_hash('sha512') }}"
      update_password: always

#fontes:
#https://stackoverflow.com/questions/45988965/change-linux-password-with-ansible-playbook-script-when-connecting-as-a-non-root
#https://www.reddit.com/r/ansible/comments/5v5a7h/changing_account_password/
